# Использование прода (нужна папка math-chat/dist)
#FROM node:22
#
# Устанавливаем рабочую директорию внутри контейнера
#WORKDIR /app
#
# Копируем всё остальное приложение внутрь контейнера
#COPY . .
#
# Запускаем
#WORKDIR /app/math-chat
#RUN npm install -g serve
#CMD ["serve", "-s", "dist", "-l", "9000"]